name: Train and Report

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run retrain script (safe)
        run: |
          python - <<'PY'
          from pathlib import Path
          p = Path('reports')
          p.mkdir(parents=True, exist_ok=True)
          with open(p / 'auto_retrain.txt','w') as f:
              f.write('Auto retrain at: ' + __import__('datetime').datetime.now().isoformat())
          print("Retrain marker written")
          PY
      - name: Upload reports artifact
        uses: actions/upload-artifact@v3
        with:
          name: TaleemAI-reports
          path: reports/
